force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Projects Assignments</relationshipLabel>
    <relationshipName>Projects_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>only active projects may be assigned</description>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Assignments</relationshipLabel>
    <relationshipName>Projects_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectTriggerTest.cls
/**
 * Created by User on 20.10.2022.
 */

@IsTest
private class ProjectTriggerTest {
    static final Integer countCreateDev =10;
    static final Integer countCreateProj =10;


    @TestSetup
    public static void createData() {
        List<Developer__c> listDev = TestDataFactory.createDevelopers(countCreateDev);
        List<Project__c> listProj = TestDataFactory.createProjects(countCreateProj, true, 100, true);
        List<Project_Assignment__c> listProjAssign = TestDataFactory.createDevelopersProjectAssignment(listDev, listProj);
    }

    //+
    @IsTest
    static void updateDevelopersFieldTotalBillableProjects() {

        Integer numEl =4;
//Before Update
        List<Developer__c> listDev = [SELECT Id, Total_Billable_Projects__c FROM Developer__c LIMIT :numEl];
        Map <Id,Developer__c> devIds = new Map<Id,Developer__c>(listDev);

        List<Project__c> listProj = [SELECT Id, Is_Billable__c FROM Project__c LIMIT :numEl];

        for(Project__c el : listProj){
            el.Is_Billable__c=false;
        }

        Test.startTest();

        update listProj;

        Test.stopTest();

        //After Update
        List<Developer__c> resListDev = [SELECT Id, Total_Billable_Projects__c FROM Developer__c WHERE Id IN :devIds.keySet()];

        for(Developer__c key: resListDev){
            System.assert(key.Total_Billable_Projects__c==(devIds.get(key.Id).Total_Billable_Projects__c-numEl));
        }
    }

}