force-app/main/default/objects/Project_Assignment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <description>dev</description>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Projects Assignments</relationshipLabel>
    <relationshipName>Projects_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>only active projects may be assigned</description>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Assignments</relationshipLabel>
    <relationshipName>Projects_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeveloperListAssignController.cls
/**
 * Created by User on 25.10.2022.
 */

public with sharing class DeveloperListAssignController {
    @AuraEnabled
    public static List<Project_Assignment__c> getProjectsAssignments(Id recordId) {
        List<Project_Assignment__c> listProjectAssignments = [
                SELECT Id,Name,CreatedDate,Project__r.Name,Project__r.Active__c,Project__r.Is_Billable__c
                FROM Project_Assignment__c
                WHERE Developer__c = :recordId
        ];
        return listProjectAssignments;
    }

    @AuraEnabled
    public static void makeSync(Id recordId) {
        try {
            DeveloperCallout.makeGetRequest(recordId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}